package com.example.data

import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject

class SchoolRepository(private val db: AppDatabase) {
    private val dao = db.schoolDao()

    // --- Flows for Reactive UI ---
    val allStudents: Flow<List<StudentEntity>> = dao.getAllStudents()
    val allTeachers: Flow<List<TeacherEntity>> = dao.getAllTeachers()
    val allParents: Flow<List<ParentEntity>> = dao.getAllParents()
    val allAttendance: Flow<List<AttendanceEntity>> = dao.getAllAttendance()
    val allHomework: Flow<List<HomeworkEntity>> = dao.getAllHomework()
    val allQuizzes: Flow<List<QuizEntity>> = dao.getAllQuizzes()
    val allExamResults: Flow<List<ExamResultEntity>> = dao.getAllExamResults()
    val allInvoices: Flow<List<FeeInvoiceEntity>> = dao.getAllInvoices()
    val allNotices: Flow<List<NoticeEntity>> = dao.getAllNotices()
    val allChatMessages: Flow<List<ChatMessageEntity>> = dao.getAllChatMessages()

    fun getStudentById(id: String): Flow<StudentEntity?> = dao.getStudentById(id)
    fun getTeacherById(id: String): Flow<TeacherEntity?> = dao.getTeacherById(id)
    fun getParentById(id: String): Flow<ParentEntity?> = dao.getParentById(id)
    fun getAttendanceForStudent(id: String): Flow<List<AttendanceEntity>> = dao.getAttendanceForStudent(id)
    fun getHomeworkForGrade(grade: String): Flow<List<HomeworkEntity>> = dao.getHomeworkForGrade(grade)
    fun getExamResultsForStudent(id: String): Flow<List<ExamResultEntity>> = dao.getExamResultsForStudent(id)
    fun getInvoicesForStudent(id: String): Flow<List<FeeInvoiceEntity>> = dao.getInvoicesForStudent(id)
    fun getConversation(id1: String, id2: String): Flow<List<ChatMessageEntity>> = dao.getConversation(id1, id2)

    // --- Writing Operations ---
    suspend fun insertStudent(student: StudentEntity) = withContext(Dispatchers.IO) { dao.insertStudent(student) }
    suspend fun insertTeacher(teacher: TeacherEntity) = withContext(Dispatchers.IO) { dao.insertTeacher(teacher) }
    suspend fun insertParent(parent: ParentEntity) = withContext(Dispatchers.IO) { dao.insertParent(parent) }
    suspend fun insertAttendance(attendance: AttendanceEntity) = withContext(Dispatchers.IO) { dao.insertAttendance(attendance) }
    suspend fun insertAttendanceList(list: List<AttendanceEntity>) = withContext(Dispatchers.IO) { dao.insertAttendanceList(list) }
    suspend fun insertHomework(homework: HomeworkEntity) = withContext(Dispatchers.IO) { dao.insertHomework(homework) }
    suspend fun deleteHomeworkById(id: Long) = withContext(Dispatchers.IO) { dao.deleteHomeworkById(id) }
    suspend fun insertQuiz(quiz: QuizEntity) = withContext(Dispatchers.IO) { dao.insertQuiz(quiz) }
    suspend fun insertExamResult(result: ExamResultEntity) = withContext(Dispatchers.IO) { dao.insertExamResult(result) }
    suspend fun insertInvoice(invoice: FeeInvoiceEntity) = withContext(Dispatchers.IO) { dao.insertInvoice(invoice) }
    suspend fun insertNotice(notice: NoticeEntity) = withContext(Dispatchers.IO) { dao.insertNotice(notice) }
    suspend fun deleteNoticeById(id: Long) = withContext(Dispatchers.IO) { dao.deleteNoticeById(id) }
    suspend fun sendChatMessage(message: ChatMessageEntity) = withContext(Dispatchers.IO) { dao.insertChatMessage(message) }

    // --- Gemini LLM Support ---
    suspend fun askGemini(prompt: String, systemInstruction: String? = null): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext "Configuration Error:\nGEMINI_API_KEY is not configured in the Secrets Panel. To enable real AI answers, please click the Secrets key icon in the left panel and set GEMINI_API_KEY with your valid key.\n\n[PROTOTYPE MODE] Here is a mock response:\n• Based on Manoj's 95% attendance & high syllabus mastery, we suggest focusing on advanced physics and solving past CBSE Math board papers.\n• Study Plan: 45m Algebra, 15m review daily."
        }

        try {
            val reqParts = listOf(GeminiPart(text = prompt))
            val contents = listOf(GeminiContent(parts = reqParts))
            val systemContent = systemInstruction?.let {
                GeminiContent(parts = listOf(GeminiPart(text = it)))
            }
            val request = GeminiReq(contents = contents, systemInstruction = systemContent)
            
            val response = RetrofitClient.apiService.generateContent(apiKey, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: "No response generated by the model. Please check the prompt."
        } catch (e: Exception) {
            "AI Error:\nFailed to reach Gemini: ${e.localizedMessage ?: e.message}\n\n[FALLBACK ANSWER] Manoj is doing remarkably well with 90% in Math. Recommended resource: CBSE Chapter 6 Trigonometry Practice."
        }
    }

    // --- Seeding Default Data (Only if empty) ---
    suspend fun seedDatabaseIfEmpty() = withContext(Dispatchers.IO) {
        // Simple synchronous-style check (via flow wait or direct room count, but since it's inside IO thread we can use a helper or check existence)
        // Let's seed default students
        db.runInTransaction {
            // We do a runInTransaction block. Flow queries are asynchronous, but let's see if we can do transactional check
            // E.g. we can insert if not already present.
        }
    }

    suspend fun seedMockData(force: Boolean = false) = withContext(Dispatchers.IO) {
        // Pre-loaded seed list
        val students = listOf(
            StudentEntity("s1", "Manoj Kumar Rath", "12", "Grade 10", "Section A", "p1", "manoj.rath@cbse.in", "https://api.dicebear.com/7.x/adventurer/svg?seed=Manoj", "A very diligent, sincere, and bright student. Always eager to participate in quizzes."),
            StudentEntity("s2", "Subhasmita Nayak", "08", "Grade 10", "Section A", "p2", "subhasmita.nayak@cbse.in", "https://api.dicebear.com/7.x/adventurer/svg?seed=Subhasmita", "Active in cultural events and House System activities. Strong in Science."),
            StudentEntity("s3", "Priyanka Panda", "15", "Grade 9", "Section B", "p3", "priyanka.panda@cbse.in", "https://api.dicebear.com/7.x/adventurer/svg?seed=Priyanka", "Keen library reader. Needs to focus slightly more on math homework.")
        )
        dao.insertStudents(students)

        val teachers = listOf(
            TeacherEntity("t1", "Mr. Rajesh Mohanty", "Mathematics", "rajesh.math@publicschool.edu", "+91 94370 12345", "https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh"),
            TeacherEntity("t2", "Mrs. Snehalata Sahu", "Science & Biology", "snehalata.sci@publicschool.edu", "+91 94372 67890", "https://api.dicebear.com/7.x/avataaars/svg?seed=Snehalata"),
            TeacherEntity("t3", "Mr. Swadhin Pradhan", "Computer Applications", "swadhin.comp@publicschool.edu", "+91 94375 55443", "https://api.dicebear.com/7.x/avataaars/svg?seed=Swadhin")
        )
        dao.insertTeachers(teachers)

        val parents = listOf(
            ParentEntity("p1", "Mr. Alok Rath", "s1", "alok.rath@parent.in", "+91 99381 22334"),
            ParentEntity("p2", "Mrs. Minati Nayak", "s2", "minati.nayak@parent.in", "+91 99385 44556"),
            ParentEntity("p3", "Mr. Bimal Panda", "s3", "bimal.panda@parent.in", "+91 99389 77889")
        )
        dao.insertParents(parents)

        val notices = listOf(
            NoticeEntity(0, "Academic Session Reopening 2026-27", "The school will reopen for the new academic session on June 16, 2026. All students must report in full summer uniform with books. Morning assembly begins at 7:30 AM sharp.", "Circular", "2026-06-05", "High"),
            NoticeEntity(0, "FEE REMINDER - 1st Quarter Dues", "Dear Parents, please note that the due date for the payment of the First Quarter School Fee (June-August 2026) is June 15, 2026. Avoid late charges by paying online via the Parent Portal.", "Emergency", "2026-06-04", "High"),
            NoticeEntity(0, "Inter-House Science & IT Exhibition", "Our Legal Literacy Club and IT Wing are combinedly organizing the Grand Science & Coding Fair on July 2, 2026. Main theme is 'AI for Rural Empowerment & Social Justice'. Models, working prototype, or coding solutions are welcome.", "Event", "2026-06-02", "Normal"),
            NoticeEntity(0, "Summer Vacation & Remedial Plan", "Summer remedial support classes for Board batch (Grade 10) are successfully completed. Principal wishes all students happy and active holidays.", "Holiday", "2026-05-20", "Normal")
        )
        dao.insertNotices(notices)

        val homeworks = listOf(
            HomeworkEntity(0, "Quadratic Equations Board Problems", "Complete exercise 4.3 and 4.4 from NCERT textbook and solve the 5 previous year CBSE board question papers in your math notebook.", "Mathematics", "Grade 10", "2026-06-12", "t1", ""),
            HomeworkEntity(0, "Ray Diagrams of Concave & Convex Mirrors", "Draw complete ray diagrams for all 6 cases of image formation by concave mirrors. Submit high quality pictures of your neat pencil sketches.", "Science & Biology", "Grade 10", "2026-06-15", "t2", ""),
            HomeworkEntity(0, "Basic Web Page in HTML & CSS", "Write an HTML code snippet of a school website homepage with structured header, main body of school details, and footer.", "Computer Applications", "Grade 10", "2026-06-18", "t3", "")
        )
        for (hw in homeworks) dao.insertHomework(hw)

        val invoices = listOf(
            FeeInvoiceEntity(0, "s1", "1st Quarter Tuition & Development Fee", 4500.0, "2026-06-15", "Pending"),
            FeeInvoiceEntity(0, "s1", "CBSE Board Examination Seat Booking Fee", 1500.0, "2026-05-10", "Paid", "2026-05-09", "PS-982310"),
            FeeInvoiceEntity(0, "s2", "1st Quarter Tuition & Development Fee", 4500.0, "2026-06-15", "Paid", "2026-06-01", "PS-982420"),
            FeeInvoiceEntity(0, "s3", "1st Quarter Tuition & Development Fee", 4200.0, "2026-06-15", "Pending")
        )
        dao.insertInvoices(invoices)

        val examResults = listOf(
            ExamResultEntity(0, "s1", "Mathematics", "Unit Test-I", 23.5, 25.0, "A+", "Term I"),
            ExamResultEntity(0, "s1", "Science & Biology", "Unit Test-I", 24.0, 25.0, "A+", "Term I"),
            ExamResultEntity(0, "s1", "Computer Applications", "Unit Test-I", 25.0, 25.0, "A+", "Term I"),
            ExamResultEntity(0, "s1", "Mathematics", "Half-Yearly Examination", 74.0, 80.0, "A", "Term I"),
            ExamResultEntity(0, "s1", "Science & Biology", "Half-Yearly Examination", 76.5, 80.0, "A+", "Term I")
        )
        dao.insertExamResults(examResults)

        // Seed some default attendance records for past few days for student s1, s2, s3
        val attendance = listOf(
            AttendanceEntity(0, "s1", "2026-06-01", "Present"),
            AttendanceEntity(0, "s1", "2026-06-02", "Present"),
            AttendanceEntity(0, "s1", "2026-06-03", "Late", 10),
            AttendanceEntity(0, "s1", "2026-06-04", "Present"),
            AttendanceEntity(0, "s1", "2026-06-05", "Present"),
            
            AttendanceEntity(0, "s2", "2026-06-01", "Present"),
            AttendanceEntity(0, "s2", "2026-06-02", "Absent"),
            AttendanceEntity(0, "s2", "2026-06-03", "Present"),
            AttendanceEntity(0, "s2", "2026-06-04", "Present"),
            AttendanceEntity(0, "s2", "2026-06-05", "Present"),

            AttendanceEntity(0, "s3", "2026-06-01", "Present"),
            AttendanceEntity(0, "s3", "2026-06-02", "Present"),
            AttendanceEntity(0, "s3", "2026-06-03", "Present"),
            AttendanceEntity(0, "s3", "2026-06-04", "Present"),
            AttendanceEntity(0, "s3", "2026-06-05", "Late", 15)
        )
        dao.insertAttendanceList(attendance)

        val quizQuestionsList = """
            [
               {
                 "id": 1,
                 "questionText": "What is the common difference of the AP: 3, 7, 11, 15...?",
                 "options": ["2", "4", "6", "11"],
                 "correctAnswerIndex": 1
               },
               {
                 "id": 2,
                 "questionText": "If one root of quadratic equation 2x² + kx - 6 = 0 is 2, value of k is?",
                 "options": ["1", "-1", "2", "-2"],
                 "correctAnswerIndex": 1
               }
            ]
        """.trimIndent()
        
        val q1 = QuizEntity(
            title = "Maths Class X: Chapter 4 (Quadratic & AP)",
            description = "Quick self-assessment for Grade 10 students prepared by Mr. Rajesh Mohanty. Covers CBSE sample problems.",
            subject = "Mathematics",
            grade = "Grade 10",
            questionsJson = quizQuestionsList
        )
        dao.insertQuiz(q1)

        val scienceQuizCode = """
            [
               {
                 "id": 1,
                 "questionText": "Which type of mirror is used as a shaving mirror and dental probe?",
                 "options": ["Convex Mirror", "Concave Mirror", "Plane Mirror", "None of these"],
                 "correctAnswerIndex": 1
               },
               {
                 "id": 2,
                 "questionText": "What is the function of pupil in the human eye?",
                 "options": ["Focuses light", "Protects eyeball", "Regulates amount of entering light", "Sends electric signal"],
                 "correctAnswerIndex": 2
               }
            ]
        """.trimIndent()
        
        val q2 = QuizEntity(
            title = "Science Class X: Chapter 10 & 11 (Light Physics)",
            description = "Quick self-assessment for Light Reflection & Human Eye. Handcrafted CBSE standard questions.",
            subject = "Science & Biology",
            grade = "Grade 10",
            questionsJson = scienceQuizCode
        )
        dao.insertQuiz(q2)
    }
}
